spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/onepage?useUnicode=true&characterEncoding=utf8
    username: developer
    password: developer
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: true
    hibernate:
      naming:
        strategy: org.hibernate.cfg.EJB3NamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 8080
cloudinary:
  name: one-person
  key: 487777781641271
  secret: QbNKLC0FwKGQ-Cy2tUNLoEjfyyc